### PR TITLE
Block credit card ads from e-food.gr

### PR DESCRIPTION
**Pull request by gkaklas**

### CODE REVIEW

**Comment by kargig** [comment]
This is even tougher call than PR #25 . No links at all, but a popup regarding an offer of the same site.

Can you add some more information/explanation why this should be considered an ad that we need to block ?

thanks

**Comment by gkaklas** [comment]
- www.e-food.gr##.promo-message--visible.promo-message.hidden-xs

On the [frontpage](https://www.e-food.gr), the small popup on the bottom right

- www.e-food.gr##.clearfix.order-form-section-mastercard.order-form-section.order-top

After you have completed an order (at the top of the page), when selecting payment methods etc.

- www.e-food.gr##.modal-header > .clearfix

On the popup in which you select the credit card for making the payment

- www.e-food.gr##.alert-notice-mastercard.alert-notice.alert

After completing the order, under the message that tells you the order has been made successfully 

(Sorry for not providing URLs, they are very specific to the user's steps and are not reproducible/reusable)

**Comment by gkaklas** [comment]
One thing that we could do to honor the offer for people who can benefit from it, is to hide some of these promos and keep the one which is most useful, like the one right before you pay for your order.
I'm suggesting this as a brainstorming, I'm not sure if such a decision is to be made from an ad filter which maintains a neutral POV. However, if it is displayed only once it isn't so annoying and can be considered as an offer that may seem useful to the user.

Thanks

**Comment by kargig** [comment]
I will close this PR without merging the commit.

I asked quite a few people and nobody else thought of this practice of e-food.gr as "annoying", most did not even consider it as an "advertisement". Popups can definitely be annoying sometimes but this is an 'annoying ads filter' not a UI/UX modifier.

Also it doesn't really force you to do something, and is 'opt-in'.

Thank you for your efforts though and I hope you'll keep sending PRs!

**Comment by gkaklas** [comment]
Ok, thanks for considering it :)
Glad I was able to contribute with the other PR, I will send another one if I find anything!

**Pull request closed without merging**
