### PR TITLE
Add skroutz.gr sponsored items

### PR DESCRIPTION
**Pull request by glogiotatidis**
Block sponsored items from `skroutz.gr`

Fixes: #112

### CODE REVIEW

**Comment by kargig** [comment]
while I also block these personally in my browser, I don't think they are "ads", they are not trying to send you to other sites.
In the past we've avoided adding such rules to the main greek adblock list.

We could maybe create a new "annoyances" list that includes such rules

**Comment by glogiotatidis** [comment]
Hmmm, I see your point about not sending you to another site but they are ads since they affect the sorting and are paid to be there. In my mind they are the same as the google ads in the search results.

If you feel strongly about not including it here though, an "annoyances" list can work.

**Comment by pshlos46** [comment]
I also agree. Those are paid ads, same as the "promoted"m results in any search engine. 
You find the exact same products below in lower prices, so I works kind of "against" the end user.
I agree in adding it either in the main list, or in an extra "annoyances" list as you said.

**Comment by epigramx** [comment]
They are ads, and they manipulate the visitor, to have the delusion they are not ads (the 'sponsored' text is easy to miss at first).

**Comment by pappasadrian** [comment]
> I don't think they are "ads", they are not trying to send you to other sites. 

I will respectfully disagree. Certain businesses pay to get their own listing higher up in the list results. They are relevant to the search results, but they are still ads. 

Skroutz itself promotes these sort of listings as ads. See their advertising options document, p. 2 and 7
https://www.skroutz.gr/media/Skroutz-Advertising-Options-2021-eng.pdf

Other advertisers recognize sponsored listings as ads as well. See for example:
https://www.kevel.com/blog/sponsored-listings/
https://koddi.com/an-introduction-to-sponsored-listings/

> We could maybe create a new "annoyances" list that includes such rules

That might be useful, indeed

**Comment by epigramx** [comment]
I don't think it's a debate. They would not be ads only if you can't see those products at all in the list.
They are right there in the list right below them again so they have 0 reason other than to be ads.

**Comment by epigramx** [comment]
It might need an extra filter, possibly because of login vs non-login.
```
www.skroutz.gr##.labeled-item.with-skus-slider.card.cf
www.skroutz.gr##li.labeled-product.labeled-item.card.cf
```

**Review by kargig — APPROVED** [review]
approved

**Comment by kargig** [comment]
There's a lot of interest for this PR. I've reconsidered and I decided to approve the changes.
I'm using the suggestion from @epigramx to replace the original PR contents that @glogiotatidis had provided and it seems not to work any more.

Thank you all for your comments and patience

**Pull request merged**
