### PR TITLE
Added rules for veriotis.gr

### PR DESCRIPTION
**Pull request by nfoustanas**

### CODE REVIEW

**Comment by kargig** [comment]
I think there's a simpler way, can you try this:
```
www.veriotis.gr###crosscol-overflow
www.veriotis.gr##.column-left-outer
www.veriotis.gr##.column-right-outer
www.veriotis.gr###main > .HTML.widget
```

if it works for you, please change your PR

**Comment by nfoustanas** [comment]
> 
> 
> I think there's a simpler way, can you try this:
> 
> ```
> www.veriotis.gr###crosscol-overflow
> www.veriotis.gr##.column-left-outer
> www.veriotis.gr##.column-right-outer
> www.veriotis.gr###main > .HTML.widget
> ```
> 
> if it works for you, please change your PR

I thought about that as well but the problem with removing `.column-left-outer` and `.column-right-outer` is that some other useful divs are lost (which are not ads). These are visible on the screenshot below:

veriotis-columns

Also the following rule is needed:

`veriotis.gr##.grey.without-text.right.bottom`

 in order to block the ad on the bottom right of the page:

veriotis-ad


Other than that, the following lines
```
veriotis.gr###HTML38
veriotis.gr###HTML14
```
can be replaced with this rule of course:
`veriotis.gr###main > .HTML.widget`

I made a new PR with this change now

**Comment by kargig** [comment]
> > I think there's a simpler way, can you try this:
> > ```
> > www.veriotis.gr###crosscol-overflow
> > www.veriotis.gr##.column-left-outer
> > www.veriotis.gr##.column-right-outer
> > www.veriotis.gr###main > .HTML.widget
> > ```
> > 
> > 
> > if it works for you, please change your PR
> 
> I thought about that as well but the problem with removing `.column-left-outer` and `.column-right-outer` is that some other useful divs are lost (which are not ads). These are visible on the screenshot below:
> 
> [snip]
> 
> I changed the PR with a new commit now reflecting this change

you're right. @aldi any other suggestions maybe ?

**Comment by aldi** [comment]
@nfoustanas @kargig 
I don't think that filtering temporary ids or classes would be a good idea. Maybe tomorrow, the site administrator will add new ids making us do double work.

I examined the sidebar ads and found that almost all (except the last one, thus adding ``:not(:last-child)``) have a direct div child). The acceptable ads have a direct h2 tag instead.
So I came up with this:
``veriotis.gr##.HTML.widget:not(:last-child)> div:first-child``
What do you think?

**Comment by nfoustanas** [comment]
> 
> 
> @nfoustanas @kargig
> I don't think that filtering temporary ids or classes would be a good idea. Maybe tomorrow, the site administrator will add new ids making us do double work.
> 
> I examined the sidebar ads and found that almost all (except the last one, thus adding `:not(:last-child)`) have a direct div child). The acceptable ads have a direct h2 tag instead.
> So I came up with this:
> `veriotis.gr##.HTML.widget:not(:last-child)> div:first-child`
> What do you think?

@aldi  @kargig 
Yes, that's much better of course. So, to hide all ads we need these 3 lines:

```
veriotis.gr###crosscol-overflow
veriotis.gr##.HTML.widget:not(:last-child)> div:first-child
veriotis.gr##div[id^="epom-"]
```

I also improved `veriotis.gr##.grey.without-text.right.bottom`

and wrote this rule instead:

`veriotis.gr##div[id^="epom-"]`

The div containing the bottom right ad has a random id that always starts with `epom-` . So this should also work even if the class names change in the future.

**Comment by aldi** [comment]
@nfoustanas Looks good!

**Review by aldi — APPROVED** [review]

**Comment by kargig** [comment]
great job @aldi and @nfoustanas, thank you!

**Pull request merged**
